[2024-07-29 17:45:58,922] {processor.py:153} INFO - Started process (PID=173) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:45:58,930] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:45:58,937] {logging_mixin.py:115} INFO - [2024-07-29 17:45:58,936] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:45:59,125] {logging_mixin.py:115} INFO - [2024-07-29 17:45:59,110] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:45:59,128] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:45:59,253] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.370 seconds
[2024-07-29 17:46:10,359] {processor.py:153} INFO - Started process (PID=178) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:46:10,360] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:46:10,361] {logging_mixin.py:115} INFO - [2024-07-29 17:46:10,361] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:46:10,924] {logging_mixin.py:115} INFO - [2024-07-29 17:46:10,919] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:46:10,926] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:46:11,440] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 1.085 seconds
[2024-07-29 17:46:21,854] {processor.py:153} INFO - Started process (PID=183) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:46:21,855] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:46:21,881] {logging_mixin.py:115} INFO - [2024-07-29 17:46:21,881] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:46:21,943] {logging_mixin.py:115} INFO - [2024-07-29 17:46:21,938] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:46:21,966] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:46:22,018] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.169 seconds
[2024-07-29 17:46:32,781] {processor.py:153} INFO - Started process (PID=188) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:46:32,796] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:46:32,822] {logging_mixin.py:115} INFO - [2024-07-29 17:46:32,822] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:46:32,909] {logging_mixin.py:115} INFO - [2024-07-29 17:46:32,903] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:46:32,913] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:46:34,424] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 1.690 seconds
[2024-07-29 17:46:45,523] {processor.py:153} INFO - Started process (PID=193) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:46:45,528] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:46:45,534] {logging_mixin.py:115} INFO - [2024-07-29 17:46:45,534] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:46:45,697] {logging_mixin.py:115} INFO - [2024-07-29 17:46:45,679] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:46:45,710] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:46:45,865] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.371 seconds
[2024-07-29 17:46:57,473] {processor.py:153} INFO - Started process (PID=198) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:46:57,478] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:46:57,483] {logging_mixin.py:115} INFO - [2024-07-29 17:46:57,482] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:46:57,654] {logging_mixin.py:115} INFO - [2024-07-29 17:46:57,644] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:46:57,667] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:46:58,109] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.723 seconds
[2024-07-29 17:47:09,629] {processor.py:153} INFO - Started process (PID=203) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:47:09,648] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:47:09,674] {logging_mixin.py:115} INFO - [2024-07-29 17:47:09,674] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:47:09,995] {logging_mixin.py:115} INFO - [2024-07-29 17:47:09,916] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:47:10,001] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:47:10,162] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.577 seconds
[2024-07-29 17:47:20,313] {processor.py:153} INFO - Started process (PID=208) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:47:20,324] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:47:20,330] {logging_mixin.py:115} INFO - [2024-07-29 17:47:20,327] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:47:20,867] {logging_mixin.py:115} INFO - [2024-07-29 17:47:20,477] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:47:20,877] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:47:21,171] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.866 seconds
[2024-07-29 17:47:31,344] {processor.py:153} INFO - Started process (PID=213) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:47:31,394] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:47:31,395] {logging_mixin.py:115} INFO - [2024-07-29 17:47:31,395] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:47:32,080] {logging_mixin.py:115} INFO - [2024-07-29 17:47:31,997] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:47:32,114] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:47:32,380] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 1.045 seconds
[2024-07-29 17:47:43,405] {processor.py:153} INFO - Started process (PID=218) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:47:44,104] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:47:44,108] {logging_mixin.py:115} INFO - [2024-07-29 17:47:44,108] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:47:44,512] {logging_mixin.py:115} INFO - [2024-07-29 17:47:44,504] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:47:44,514] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:47:44,727] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 1.373 seconds
[2024-07-29 17:47:54,879] {processor.py:153} INFO - Started process (PID=223) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:47:54,889] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:47:54,893] {logging_mixin.py:115} INFO - [2024-07-29 17:47:54,893] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:47:54,996] {logging_mixin.py:115} INFO - [2024-07-29 17:47:54,986] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:47:54,999] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:47:55,091] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.221 seconds
[2024-07-29 17:48:05,899] {processor.py:153} INFO - Started process (PID=228) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:48:05,924] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:48:05,925] {logging_mixin.py:115} INFO - [2024-07-29 17:48:05,925] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:48:06,102] {logging_mixin.py:115} INFO - [2024-07-29 17:48:06,075] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:48:06,106] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:48:07,631] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 1.745 seconds
[2024-07-29 17:48:17,942] {processor.py:153} INFO - Started process (PID=233) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:48:18,103] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:48:18,104] {logging_mixin.py:115} INFO - [2024-07-29 17:48:18,104] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:48:19,866] {logging_mixin.py:115} INFO - [2024-07-29 17:48:19,861] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:48:19,867] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:48:20,015] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 2.081 seconds
[2024-07-29 17:48:30,644] {processor.py:153} INFO - Started process (PID=238) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:48:32,993] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:48:32,994] {logging_mixin.py:115} INFO - [2024-07-29 17:48:32,994] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:48:33,124] {logging_mixin.py:115} INFO - [2024-07-29 17:48:33,101] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:48:33,126] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:48:33,456] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 2.819 seconds
[2024-07-29 17:48:44,141] {processor.py:153} INFO - Started process (PID=243) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:48:44,142] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:48:44,143] {logging_mixin.py:115} INFO - [2024-07-29 17:48:44,143] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:48:44,163] {logging_mixin.py:115} INFO - [2024-07-29 17:48:44,160] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:48:44,165] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:48:44,849] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.711 seconds
[2024-07-29 17:48:55,630] {processor.py:153} INFO - Started process (PID=248) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:48:55,643] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:48:55,644] {logging_mixin.py:115} INFO - [2024-07-29 17:48:55,644] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:48:55,690] {logging_mixin.py:115} INFO - [2024-07-29 17:48:55,680] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:48:55,692] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:48:55,757] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.131 seconds
[2024-07-29 17:49:05,898] {processor.py:153} INFO - Started process (PID=253) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:49:05,909] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:49:05,911] {logging_mixin.py:115} INFO - [2024-07-29 17:49:05,910] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:49:05,952] {logging_mixin.py:115} INFO - [2024-07-29 17:49:05,947] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:49:05,953] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:49:06,005] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.110 seconds
[2024-07-29 17:49:17,181] {processor.py:153} INFO - Started process (PID=258) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:49:17,182] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:49:17,183] {logging_mixin.py:115} INFO - [2024-07-29 17:49:17,183] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:49:17,204] {logging_mixin.py:115} INFO - [2024-07-29 17:49:17,200] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:49:17,205] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:49:19,588] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 2.415 seconds
[2024-07-29 17:49:31,775] {processor.py:153} INFO - Started process (PID=263) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:49:31,779] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:49:31,780] {logging_mixin.py:115} INFO - [2024-07-29 17:49:31,780] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:49:31,817] {logging_mixin.py:115} INFO - [2024-07-29 17:49:31,808] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:49:31,819] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:49:31,915] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.144 seconds
[2024-07-29 17:49:42,201] {processor.py:153} INFO - Started process (PID=268) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:49:42,202] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:49:42,203] {logging_mixin.py:115} INFO - [2024-07-29 17:49:42,203] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:49:42,232] {logging_mixin.py:115} INFO - [2024-07-29 17:49:42,222] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:49:42,234] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:49:42,288] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.091 seconds
[2024-07-29 17:49:52,699] {processor.py:153} INFO - Started process (PID=273) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:49:52,734] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:49:52,735] {logging_mixin.py:115} INFO - [2024-07-29 17:49:52,735] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:49:52,809] {logging_mixin.py:115} INFO - [2024-07-29 17:49:52,804] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:49:52,810] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:49:53,007] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.312 seconds
[2024-07-29 17:50:03,267] {processor.py:153} INFO - Started process (PID=278) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:50:03,301] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:50:03,303] {logging_mixin.py:115} INFO - [2024-07-29 17:50:03,303] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:50:03,367] {logging_mixin.py:115} INFO - [2024-07-29 17:50:03,364] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:50:03,369] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:50:03,439] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.181 seconds
[2024-07-29 17:50:13,946] {processor.py:153} INFO - Started process (PID=283) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:50:13,947] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:50:13,948] {logging_mixin.py:115} INFO - [2024-07-29 17:50:13,948] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:50:13,973] {logging_mixin.py:115} INFO - [2024-07-29 17:50:13,969] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:50:13,974] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:50:14,145] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.204 seconds
[2024-07-29 17:50:24,335] {processor.py:153} INFO - Started process (PID=288) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:50:24,336] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:50:24,337] {logging_mixin.py:115} INFO - [2024-07-29 17:50:24,337] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:50:24,913] {logging_mixin.py:115} INFO - [2024-07-29 17:50:24,909] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:50:24,915] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:50:25,048] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.717 seconds
[2024-07-29 17:50:35,211] {processor.py:153} INFO - Started process (PID=293) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:50:35,269] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:50:35,271] {logging_mixin.py:115} INFO - [2024-07-29 17:50:35,270] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:50:35,404] {logging_mixin.py:115} INFO - [2024-07-29 17:50:35,400] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:50:35,406] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:50:36,131] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.924 seconds
[2024-07-29 17:50:46,271] {processor.py:153} INFO - Started process (PID=298) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:50:46,274] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:50:46,275] {logging_mixin.py:115} INFO - [2024-07-29 17:50:46,275] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:50:46,324] {logging_mixin.py:115} INFO - [2024-07-29 17:50:46,316] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:50:46,327] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:50:46,435] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.171 seconds
[2024-07-29 17:50:57,279] {processor.py:153} INFO - Started process (PID=303) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:50:57,280] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:50:57,281] {logging_mixin.py:115} INFO - [2024-07-29 17:50:57,281] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:50:57,309] {logging_mixin.py:115} INFO - [2024-07-29 17:50:57,305] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:50:57,311] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:50:57,471] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.204 seconds
[2024-07-29 17:51:09,482] {processor.py:153} INFO - Started process (PID=308) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:51:09,483] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:51:09,484] {logging_mixin.py:115} INFO - [2024-07-29 17:51:09,484] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:51:09,723] {logging_mixin.py:115} INFO - [2024-07-29 17:51:09,698] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:51:09,726] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:51:09,781] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.303 seconds
[2024-07-29 17:51:21,210] {processor.py:153} INFO - Started process (PID=313) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:51:21,336] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:51:21,612] {logging_mixin.py:115} INFO - [2024-07-29 17:51:21,383] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:51:27,564] {logging_mixin.py:115} INFO - [2024-07-29 17:51:23,335] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:51:27,812] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:51:29,108] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 8.560 seconds
[2024-07-29 17:51:40,343] {processor.py:153} INFO - Started process (PID=318) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:51:40,359] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:51:40,363] {logging_mixin.py:115} INFO - [2024-07-29 17:51:40,363] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:51:41,524] {logging_mixin.py:115} INFO - [2024-07-29 17:51:41,521] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:51:41,526] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:51:42,608] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 2.272 seconds
[2024-07-29 17:51:55,028] {processor.py:153} INFO - Started process (PID=323) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:51:55,029] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:51:55,034] {logging_mixin.py:115} INFO - [2024-07-29 17:51:55,033] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:51:55,210] {logging_mixin.py:115} INFO - [2024-07-29 17:51:55,204] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:51:55,212] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:51:55,323] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.536 seconds
[2024-07-29 17:52:05,878] {processor.py:153} INFO - Started process (PID=328) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:52:05,881] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:52:05,882] {logging_mixin.py:115} INFO - [2024-07-29 17:52:05,882] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:52:05,936] {logging_mixin.py:115} INFO - [2024-07-29 17:52:05,930] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:52:05,944] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:52:06,027] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.152 seconds
[2024-07-29 17:52:17,018] {processor.py:153} INFO - Started process (PID=333) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:52:17,332] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:52:17,335] {logging_mixin.py:115} INFO - [2024-07-29 17:52:17,335] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:52:21,737] {logging_mixin.py:115} INFO - [2024-07-29 17:52:21,709] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:52:21,739] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:52:22,313] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 5.298 seconds
[2024-07-29 17:52:32,647] {processor.py:153} INFO - Started process (PID=338) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:52:32,702] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:52:32,705] {logging_mixin.py:115} INFO - [2024-07-29 17:52:32,705] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:52:36,249] {logging_mixin.py:115} INFO - [2024-07-29 17:52:35,912] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:52:36,913] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:52:40,574] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 7.931 seconds
[2024-07-29 17:52:50,670] {processor.py:153} INFO - Started process (PID=343) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:52:50,752] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:52:50,791] {logging_mixin.py:115} INFO - [2024-07-29 17:52:50,791] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:52:52,223] {logging_mixin.py:115} INFO - [2024-07-29 17:52:52,191] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:52:52,224] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:52:53,974] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 3.320 seconds
[2024-07-29 17:53:04,263] {processor.py:153} INFO - Started process (PID=348) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:53:04,266] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:53:04,279] {logging_mixin.py:115} INFO - [2024-07-29 17:53:04,279] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:53:04,439] {logging_mixin.py:115} INFO - [2024-07-29 17:53:04,399] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:53:04,488] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:53:04,818] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.636 seconds
[2024-07-29 17:53:14,968] {processor.py:153} INFO - Started process (PID=353) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:53:15,264] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:53:15,267] {logging_mixin.py:115} INFO - [2024-07-29 17:53:15,267] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:53:15,291] {logging_mixin.py:115} INFO - [2024-07-29 17:53:15,288] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:53:15,293] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:53:17,194] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 2.230 seconds
[2024-07-29 17:53:28,904] {processor.py:153} INFO - Started process (PID=358) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:53:28,927] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:53:28,990] {logging_mixin.py:115} INFO - [2024-07-29 17:53:28,989] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:53:30,052] {logging_mixin.py:115} INFO - [2024-07-29 17:53:30,043] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:53:30,053] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:53:30,280] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 1.381 seconds
[2024-07-29 17:53:41,352] {processor.py:153} INFO - Started process (PID=363) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:53:41,355] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:53:41,633] {logging_mixin.py:115} INFO - [2024-07-29 17:53:41,616] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:53:42,758] {logging_mixin.py:115} INFO - [2024-07-29 17:53:42,358] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:53:42,760] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:53:43,148] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 2.371 seconds
[2024-07-29 17:53:56,618] {processor.py:153} INFO - Started process (PID=368) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:53:56,629] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:53:56,635] {logging_mixin.py:115} INFO - [2024-07-29 17:53:56,635] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:53:56,700] {logging_mixin.py:115} INFO - [2024-07-29 17:53:56,689] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:53:56,705] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:53:56,750] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.160 seconds
[2024-07-29 17:54:09,892] {processor.py:153} INFO - Started process (PID=373) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:54:10,189] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:54:10,193] {logging_mixin.py:115} INFO - [2024-07-29 17:54:10,193] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:54:10,228] {logging_mixin.py:115} INFO - [2024-07-29 17:54:10,223] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:54:10,229] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:54:10,384] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.557 seconds
[2024-07-29 17:54:20,656] {processor.py:153} INFO - Started process (PID=378) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:54:20,693] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:54:20,701] {logging_mixin.py:115} INFO - [2024-07-29 17:54:20,701] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:54:20,784] {logging_mixin.py:115} INFO - [2024-07-29 17:54:20,774] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:54:20,786] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:54:21,132] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.526 seconds
[2024-07-29 17:54:31,629] {processor.py:153} INFO - Started process (PID=383) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:54:31,630] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:54:31,632] {logging_mixin.py:115} INFO - [2024-07-29 17:54:31,632] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:54:32,431] {logging_mixin.py:115} INFO - [2024-07-29 17:54:32,085] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:54:32,433] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:54:35,884] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 4.258 seconds
[2024-07-29 17:54:45,959] {processor.py:153} INFO - Started process (PID=388) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:54:45,963] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:54:45,966] {logging_mixin.py:115} INFO - [2024-07-29 17:54:45,966] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:54:45,991] {logging_mixin.py:115} INFO - [2024-07-29 17:54:45,986] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:54:45,993] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:54:46,075] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.122 seconds
[2024-07-29 17:54:56,494] {processor.py:153} INFO - Started process (PID=393) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:54:56,495] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:54:56,498] {logging_mixin.py:115} INFO - [2024-07-29 17:54:56,498] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:54:56,523] {logging_mixin.py:115} INFO - [2024-07-29 17:54:56,520] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:54:56,525] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:54:56,856] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 0.426 seconds
[2024-07-29 17:55:09,907] {processor.py:153} INFO - Started process (PID=398) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:55:09,912] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:55:09,914] {logging_mixin.py:115} INFO - [2024-07-29 17:55:09,914] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:55:09,942] {logging_mixin.py:115} INFO - [2024-07-29 17:55:09,937] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:55:09,944] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:55:10,310] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 2.765 seconds
[2024-07-29 17:55:22,296] {processor.py:153} INFO - Started process (PID=403) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:55:22,350] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:55:22,352] {logging_mixin.py:115} INFO - [2024-07-29 17:55:22,352] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:55:22,436] {logging_mixin.py:115} INFO - [2024-07-29 17:55:22,426] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:55:22,439] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:55:24,020] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 1.877 seconds
[2024-07-29 17:55:34,728] {processor.py:153} INFO - Started process (PID=408) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:55:34,743] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:55:34,747] {logging_mixin.py:115} INFO - [2024-07-29 17:55:34,747] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:55:37,294] {logging_mixin.py:115} INFO - [2024-07-29 17:55:35,108] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:55:37,296] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:55:41,912] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 7.286 seconds
[2024-07-29 17:55:53,468] {processor.py:153} INFO - Started process (PID=413) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:55:58,016] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:55:58,400] {logging_mixin.py:115} INFO - [2024-07-29 17:55:58,399] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:55:58,627] {logging_mixin.py:115} INFO - [2024-07-29 17:55:58,593] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:55:58,647] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:55:59,008] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 6.665 seconds
[2024-07-29 17:56:09,947] {processor.py:153} INFO - Started process (PID=418) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:56:26,610] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:56:26,768] {logging_mixin.py:115} INFO - [2024-07-29 17:56:26,768] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:56:29,080] {logging_mixin.py:115} INFO - [2024-07-29 17:56:29,075] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:56:29,081] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:56:29,480] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 19.536 seconds
[2024-07-29 17:56:42,025] {processor.py:153} INFO - Started process (PID=423) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:56:42,031] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:56:42,038] {logging_mixin.py:115} INFO - [2024-07-29 17:56:42,038] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:56:42,223] {logging_mixin.py:115} INFO - [2024-07-29 17:56:42,206] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:56:42,239] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:56:43,469] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 1.602 seconds
[2024-07-29 17:56:57,368] {processor.py:153} INFO - Started process (PID=428) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:56:57,417] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:56:57,434] {logging_mixin.py:115} INFO - [2024-07-29 17:56:57,432] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:56:58,385] {logging_mixin.py:115} INFO - [2024-07-29 17:56:58,078] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:56:58,436] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:57:03,212] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 6.385 seconds
[2024-07-29 17:57:18,732] {processor.py:153} INFO - Started process (PID=433) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:57:25,883] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:57:25,983] {logging_mixin.py:115} INFO - [2024-07-29 17:57:25,981] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:57:28,515] {logging_mixin.py:115} INFO - [2024-07-29 17:57:28,360] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:57:28,517] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:57:38,106] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 20.222 seconds
[2024-07-29 17:57:50,217] {processor.py:153} INFO - Started process (PID=438) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:57:50,278] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:57:50,304] {logging_mixin.py:115} INFO - [2024-07-29 17:57:50,304] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:57:50,885] {logging_mixin.py:115} INFO - [2024-07-29 17:57:50,862] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:57:50,887] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:57:51,744] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 2.372 seconds
[2024-07-29 17:58:02,586] {processor.py:153} INFO - Started process (PID=443) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:58:02,621] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:58:02,638] {logging_mixin.py:115} INFO - [2024-07-29 17:58:02,638] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:58:03,279] {logging_mixin.py:115} INFO - [2024-07-29 17:58:03,201] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:58:03,289] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:58:05,123] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 2.861 seconds
[2024-07-29 17:58:21,899] {processor.py:153} INFO - Started process (PID=448) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:58:21,947] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:58:21,949] {logging_mixin.py:115} INFO - [2024-07-29 17:58:21,949] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:58:22,934] {logging_mixin.py:115} INFO - [2024-07-29 17:58:22,922] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:58:22,936] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:58:24,623] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 4.938 seconds
[2024-07-29 17:58:35,410] {processor.py:153} INFO - Started process (PID=453) to work on /opt/airflow/dags/dag.py
[2024-07-29 17:58:35,420] {processor.py:641} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-07-29 17:58:35,426] {logging_mixin.py:115} INFO - [2024-07-29 17:58:35,426] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-07-29 17:58:35,572] {logging_mixin.py:115} INFO - [2024-07-29 17:58:35,553] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from dags.etl import fetch_weather_data
ModuleNotFoundError: No module named 'dags'
[2024-07-29 17:58:35,580] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-07-29 17:58:36,527] {processor.py:161} INFO - Processing /opt/airflow/dags/dag.py took 1.263 seconds
